<script>
    function check() {
        var username = document.getElementById('username');
        var email = document.getElementById('email');
        var message = document.getElementById('message');
        var flash = document.getElementById('flash');

        var res = username.value != '' && email.value != '' && message.value != '';

        if (!res) {
            flash.innerHTML = 'Fill the fields';
        }

        return res;
    }
</script>

<b id="flash"><?=Session::getFlash()?></b>
<form class="form-signin" method="post" onsubmit="return check()">
    <h1 class="form-signin-heading">Contact</h1>
    <label for="Username" class="sr-only">Username</label>
    <input type="text" id="username"  name="username" placeholder="Username" class="form-control" value="<?=$form->username?>"><br>
    <label for="Email" class="sr-only">Email adress</label>
    <input type="email" id="email"  name="email" placeholder="Email" class="form-control" value="<?=$form->email?>"><br>
    <label for="yourMessage" class="sr-only">Email adress</label>
    <textarea name="message" id="message" placeholder="Your message" class="form-control" ><?=$form->message?></textarea><br>
    <button class="btn btn-lg btn-primary btn-block">Go</button>
</form>

