<h1>Contact</h1>

<script>
    function check() {
        var username = document.getElementById('username');
        var email = document.getElementById('email');
        var message = document.getElementById('message');
        var flash = document.getElementById('flash');

        var res = username.value != '' && email.value != '' && message.value != '';

        if (!res) {
            flash.innerHTML = 'Fill the fields';
        }

        return res;
    }
</script>

<b id="flash"><?=Session::getFlash()?></b>

<form method="post" onsubmit="return check()">
    Username: <input type="text" id="username" class="form-control" name="username" value="<?=$form->username?>"><br>
    Email: <input type="email" id="email" class="form-control" name="email" value="<?=$form->email?>"><br>
    <textarea name="message" id="message" class="form-control"><?=$form->message?></textarea><br>
    <button class="btn btn-success">Go</button>
</form>
