<script>
    function test() {
        var student = {
            name: 'Smit',
            age: 23,
            city: 'Kiev',
            status: false,

            study: function () {
                console.log('Study php');
            }
        };
        student.study();
    }
</script>

<h1>Welcome</h1>

<span onclick="test()"><?=$number?></span><br>

<a href="http://google.com" id="hello" ><?=$name?></a><br>

<script>
    var element = document.getElementById('hello');
    element.href = 'http://devionity.com';
</script>


<?php

$count = isset($_COOKIE['count']) ? (int)$_COOKIE['count'] : 0;
$count++;
setcookie('count', $count, time() + 60 * 60 * 24 * 366, '/');

?>

Hello! You visited this page <?=$count; ?> times. <br/> <!--Example cookie--!>




