<?=Session::getFlash()?>
<form class="form-signin" method="post">
    <h2 class="form-signin-heading">Please sign in</h2>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" class="form-control" placeholder="Email address" name="email" value="<?=$form->email?>"><br>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" class="form-control" placeholder="Password" name="password"><br>

    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>