<?=Session::getFlash()?>
<form class="form-signin" method="post">
    <h1 class="form-signin-heading">Register new user</h1>
    <label for="inputEmail" class="sr-only">Email adress</label>
    <input type="email" name="email" placeholder="Email adress" class="form-control"> <br>
    <label for="inputUsername" class="sr-only">Username</label>
    <input type="text" name="username" placeholder="Username" class="form-control"> <br>
    <label for="password" class="sr-only">Password</label>
    <input type="password" name="password" placeholder="Password" class="form-control"> <br>
    <label for="confirmPassword" class="sr-only">Confirm password</label>
    <input type="password" name="confirmPassword" placeholder="Confirm password" class="form-control"> <br>
    <input type="submit" class="btn btn-lg btn-primary btn-block">
</form>