<h1>Book edit</h1>
<b><?=Session::getFlash()?></b><br>
<form method="post" enctype="multipart/form-data">
    Title: <input class="form-control" type="text" name="title" value="<?= $form->title ?>"> <br>
    Price: <input class="form-control" type="text" name="price" value="<?= $form->price ?>"> <br>
    Style: <select name="style" class="form-control">
        <?php foreach ($styles as $style): ?>
            <option value="<?= $style['id'] ?>" <?= $style['id'] == $book['style_id'] ? 'selected' : '' ?> >
                <?= $style['name'] ?>
            </option>
        <?php endforeach; ?>
    </select>

    <br>
    Description: <textarea class="form-control" name="description"><?= $form->description ?></textarea>

    <input type="hidden" value="1" name="status">

<!--    <input type="file" name="document">-->

    <br>
    <button class="btn btn-success">Go</button>
</form>