<h1>Books</h1>

<table width="100%" border="1">
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Price</th>
        <th>Actions</th>
    </tr>

    <?php foreach ($books as $book): ?>
        <tr>
            <td><?= $book['id'] ?></td>
            <td><?= $book['title'] ?></td>
            <td><?= $book['price'] ?></td>
            <td>
                <a href="#">Edit</a>
                <a href="#">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>