<h1>Books</h1>

<div class="row">

    <?php foreach ($books as $book): ?>
        <div class="book-item col-sm-6 col-md-3 col-lg-2 col-xs-12">
            <div>
            Title: <?= $book['title'] ?><br>
            Author: <?= $book['author'] ?> <br>
            Price: <?= $book['price'] ?><br>
            <a href="/books/book-<?= $book['id'] ?>">Details</a>
            </div>
            <img src="/uploads/cat.jpg" alt="" class="img-responsive">
        </div>
    <?php endforeach; ?>

</div>

<?php
$page = isset($_GET['page']) ? (int)$_GET['page'] : 1;

$p = new Pagination(array(
    'itemsCount' => 99,
    'itemsPerPage' => 10,
    'currentPage' => $page
));
?>

<?php foreach ($p->buttons as $button) :
    if ($button->isActive) : ?>
        <a href = '?page=<?=$button->page?>'><?=$button->text?></a>
    <?php else : ?>
        <span style="color:#555555"><?=$button->text?></span>
    <?php endif;
endforeach; ?>

<!--<script>-->
<!--    var elements = document.getElementsByTagName('div');-->
<!--    for (key in elements) {-->
<!--        elements[key].style.display = 'None';-->
<!--    }-->
<!--</script>-->


