<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=MetaHelper::getTitle();?></title>
</head>
<body>
<a href="/">Main</a>
<a href="/books">Books</a>
<a href="/contact-us">Contact</a>
<a href="/webroot/index.php?route=cart/index">Cart</a>
|
<?php if (!Session::has('user')) :?>
    <a href="/login">Login</a>
<?php else: ?>
    <a href="/logout">Logout</a>
<?php endif; ?>
|
<a href="/register">Register</a>
<hr>
<?=$content?>
<br>
<br>
<br>
<br>
<br>
<hr>
All rights reserved &copy; 2016
</body>
</html>