<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MVC mega site</title>
</head>
<body>
<a href="/">Main</a>
<a href="/index.php?route=book/index">Books</a>
<a href="/index.php?route=index/contact">Contact</a>
|
<?php if (!Session::has('user')) :?>
    <a href="/index.php?route=security/login">Login</a>
<?php else: ?>
    <a href="/index.php?route=security/logout">Logout</a>
<?php endif; ?>
<hr>
<?=$content?>
<br>
<br>
<br>
<br>
<br>
<hr>
All rights reserved &copy; 2016
</body>
</html>